### ISSUE TITLE
Re-do Footer

### ISSUE THREAD

**Issue by jrec15** [rocketpastsix/transparentcoffee#3]
Should be the mostly the same. I notice the current one is a little buggy though with a blank space that's really a "go to top of page" button.

**Comment by matthewtrask** [comment]
I merged this on dev, can you take a look and make sure the code looks good. just mimic'd their footer. added some styling.

**Comment by jrec15** [comment]
Looks good to me for the most part. Higher quality than the old site which i like. Only thing I see is for some reason "About" isnt working as a link for me (nothing when hovering over it), and on the old site a couple of them were fly out dropdown kind of styles which we might want to mimic
